name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest memory_profiler  # Include memory_profiler here
        # Include any other dependencies your tests might require


    - name: List files
      run: |
        ls -la  # Verify that example.db is present

    - name: Run script
      run: |
        python test.py
    
    - name: Format
      run: |
        pip install black
        black --check .

    - name: Lint
      run: |
        pip install flake8
        flake8 .

    - name: Tests
      run: |
        pip install pytest
        pytest test.py -vv